### 파이썬에서 데이터분석(전처리, 가공)을 하기 위해 Pandas라는 라이브러리를 활용함.
#### Pandas -> Panel Data
#### 데이터 분석 - 표 형태로 이루어진 데이터에서 결측치와 이상치를 제거하고, 데이터를 가공, 정규화하여 데이터에서 유의미한 정보 및 지식, 지혜를 얻는 작업

In [ ]:
# 판다스 사용을 위해서는 최초 한 번 판다스를 설치해야한다.
# 한번만 하면 계속 쓸 수 있다.
!pip install pandas

Requirement already satisfied: pandas in C:\Users\GRS\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\GRS\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\GRS\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\GRS\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\GRS\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# 엑셀 파일의 데이터를 읽어오거나, 데이터를 엑셀 파일로 저장하기 위한 라이브러리도 추가 설치
# 한번만 하면 계속 쓸 수 있다.
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\GRS\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\GRS\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)

In [3]:
# pandas 라이브러리를 사용하기 위해서는 import를 우선 진행한다.
# import pandas만 작성해도 import할 수 있다. as pd를 붙이면 pd를 별칭으로 함수를 편하게 쓸 수 있다. ex) pd.함수()
# pandas 라이브러리를 import하고, 사용시 pd라는 이름으로 사용하겠다는 명령어
import pandas as pd

In [4]:
# pandas 사용을 위한 데이터 딕셔너리 데이터
data = {
  '이름' : ['김자바', '이자바', '박자바', '최캐드', '정캐드']
  , '학급' : ['자바반','자바반','자바반','캐드반','캐드반']
  , '국어점수' : [90, 80, 70, 100, 90]
  , '영어점수' : [70, 80, 80, 70, 90]
  , '평균' : [80.0,80.0,75.0,85.0,90.0]
  , '취미' : ['독서','','','요가','축구']
}

#위 딕셔너리 데이터를 DataFrame(표 형태)으로 변환
df = pd.DataFrame(data)

In [6]:
#데이터 확인
df

    이름   학급  국어점수  영어점수    평균  취미
0  김자바  자바반    90    70  80.0  독서
1  이자바  자바반    80    80  80.0
2  박자바  자바반    70    80  75.0
3  최캐드  캐드반   100    70  85.0  요가
4  정캐드  캐드반    90    90  90.0  축구

In [12]:
#df 데이터를 엑셀 파일로 저장
# 행 번호도 컬럼 데이터로 저장된다.
# 엑셀파일로 변환시 행번호는 제외시킬 수 있다.
# to_excel()함수의 두번째 매개변수로 index = False를 주면 된다.
# 파이썬의 true, false의 앞 문자가 대문자여야한다. True, False

df.to_excel('test2.xlsx', index = False)

In [13]:
#저장된 엑셀 파일 불러오기
new_df = pd.read_excel('test2.xlsx')

new_df

    이름   학급  국어점수  영어점수  평균   취미
0  김자바  자바반    90    70  80   독서
1  이자바  자바반    80    80  80  NaN
2  박자바  자바반    70    80  75  NaN
3  최캐드  캐드반   100    70  85   요가
4  정캐드  캐드반    90    90  90   축구

In [14]:
#data.xlsx 파일 읽어오기
df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
#데이터 기본 정보 확인
#빈문자를 NaN으로 나오고 그것을 null로 인식한다.
df.info()

#상위 5개의 데이터 조회
#어떤 데이터가 들어가 있는지 확인하는 용도
df.head()

#행과 열의 갯수를 파악(데이터 갯수 파악하기 위해 사용)
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   반       10 non-null     str
 1   이름      10 non-null     str
 2   성별      10 non-null     str
 3   국어      7 non-null      float64
 4   수학      7 non-null      float64
 5   응시여부    8 non-null      str
 6   확인여부    7 non-null      str
dtypes: float64(2), str(5)
memory usage: 692.0 bytes

(10, 7)