In [ ]:
#매번 import 해줘야 판다스를 쓸 수 있다.
import pandas as pd

In [2]:
df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
#특정 컬럼 데이터만 조회하기 
#리스트에 감싸지 않아도 되지만 리스트로 감싸면 표 형태로 출력된다.
#데이터가 하나더라도 리스트로 감싸는게 낫다
df['국어']
df[['국어']]

#이름, 국어 컬럼만 조회(여러 컬럼 조회시 컬럼명을 리스트 형태로!)
#두 컬럼을 하나로 묶기 위해서 []로 리스트로 만들어 넣는다.
df[['이름','국어']]

     국어
0  90.0
1  78.0
2   NaN
3  33.0
4   0.0
5   NaN
6  90.0
7  78.0
8   NaN
9  86.0

In [ ]:
#특정 열과 행 데이터 조회
# 1. df.loc[행번호, 열이름] 이게 가독성이 좋다
# 2. df.iloc[행번호, 열번호]

#열이름 안 넣으면 전체로
df.loc[2] # 2번 행 데이터 조회
df.loc[1:4] # 1~4번 행 데이터 조회
df.loc[1:] # 1번 부터 전체 행 데이터 조회

df.loc[0, '이름'] # 0번 행의 이름 컬럼 조회
df.loc[0, ['이름']] 
df.loc[1:4,['이름','성별']] # 1~4번 행의 이름, 성별 데이터 조회

df.iloc[1:3,[0,2]] #1~3번 행의 0번 컬럼, 2번 컬럼을 조회
df.iloc[:, 1:5] #1~5번 열 조회 열 이름 적을게 많으면 쓰기도 하지만 많이 쓰지는 않는다.

    이름 성별    국어     수학
0  구이서  남  90.0   89.0
1  김이정  여  78.0   45.0
2  오지수  남   NaN    NaN
3  김선후  남  33.0   44.0
4  하진희  여   0.0   85.0
5  강현진  남   NaN    NaN
6  김진솔  남  90.0   89.0
7  박서준  여  78.0   45.0
8  김성희  남   NaN    NaN
9  이지서  여  86.0  100.0

In [ ]:
#특정 조건에 만족하는 데이터를 조회 
#이 걸 가장 많이 씀
#국어 점수가 80점 이상인 데이터 조회
#1. 국어 점수가 80점 이상이라는 조건
df['국어'] >= 80

#2. 만든 조건을 적용하는 코드
df[df['국어'] >= 80] #행을 걸러내기 힘듯

# 위와 같은 코드를 loc를 사용
df.loc[df['국어'] >= 80 ]

#성별이 '여'인 데이터만 조회
df[ df['성별'] == '여' ]
df.loc[df['성별'] == '여' , ['이름','성별']]

#조건이 여러개일 경우
#국어가 80점 이상이면서, 성별은 '여'인 학생 정보 조회
#1. 국어가 80이상
condition1 = df['국어'] >= 80
#2. 성별이 '여'인 조건
condition2 = df['성별'] == '여'
df[condition1 & condition2]
#여러개의 조건을 직접 작성하려면 조건을 무조건 소괄호에 감싸야한다.
df[(df['국어'] >= 80) & (df['성별'] == '여')]

#df.loc[행정보, 열정보] & = and , | = or 
df.loc[condition1 & condition2]
df.loc[(df['국어'] >= 80) & (df['성별'] == '여')]


#팁 조건에 맞는 데이터 조회시 quert() 함수(행만 구분) 사용할 수 있음
df.query('국어 >= 80')
df.query('성별 == "남"')
df.query('국어 >= 80 and 성별 == "여"')

    반   이름 성별    국어     수학 응시여부 확인여부
9  B반  이지서  여  86.0  100.0   응시   확인