In [ ]:
#데이터 정렬
#정렬기준이 되는 컬럼에 여러 컬럼 넣으려면 리스트로 []해야한다.
#ascending 오름차순 True -> 오름차순 False -> 내림차순
#df.sort_values(by=[정렬 기준이 되는 컬럼], ascending=True) 이 함수를 많이 쓴다.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
#'이름' 컬럼 기준으로 오름차순 정렬
#하나의 기준으로는 리스트 쓰지 않아도 되지만 편하게 하려면 쓰는게 좋다
df.sort_values(by='이름', ascending=True)
df.sort_values(by=['이름'], ascending=[True])

    반   이름 성별    국어     수학 응시여부 확인여부
5  A반  강현진  남   NaN    NaN  NaN  NaN
0  A반  구이서  남  90.0   89.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
8  A반  김성희  남   NaN    NaN  NaN   확인
1  B반  김이정  여  78.0   45.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
4  A반  하진희  여   0.0   85.0   응시  NaN

In [7]:
#'반' 기준으로 내림차순 정렬 후 이름 기준 오름차순 정렬
df.sort_values(by=['반', '이름'], ascending=[False, True])

    반   이름 성별    국어     수학 응시여부 확인여부
3  B반  김선후  남  33.0   44.0   응시  NaN
1  B반  김이정  여  78.0   45.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
5  A반  강현진  남   NaN    NaN  NaN  NaN
0  A반  구이서  남  90.0   89.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
2  A반  오지수  남   NaN    NaN   응시   확인
4  A반  하진희  여   0.0   85.0   응시  NaN

In [ ]:
#데이터 집계

In [8]:
#전체적인 집계, 통계 확인
df.describe()

             국어          수학
count   7.00000    7.000000
mean   65.00000   71.000000
std    34.82815   25.053277
min     0.00000   44.000000
25%    55.50000   45.000000
50%    78.00000   85.000000
75%    88.00000   89.000000
max    90.00000  100.000000

In [9]:
# '반' 컬럼의 카테고리별 데이터 확인
df['반'].value_counts()

반
A반    5
B반    5
Name: count, dtype: int64

In [ ]:
# 특정 컬럼의 집계 정보 확인

#'국어' 점수의 합
#df['국어'].sum() -> 합이 나오긴 하지만 숫자 형태가 아님 

#집계 데이터를 숫자형태로 보기 위한 방법 
#출력과 변수 등의 데이터 사용을 위해 변환하는 방법을 추천한다.
float(df['국어'].sum()) #데이터를 실수형으로 변환, 정수변환:int(), 실수변환:float()
float(df['국어'].mean()) #평균
float(df['국어'].max()) #최대값
float(df['국어'].min()) #최소값
float(df['국어'].count()) #갯수
float(df['국어'].median()) #중앙값

#여러 컬럼의 통계를 한 번에 확인할 수 있다.
#이렇게 하면 값을 뽑아쓰지는 못해 위처럼 한다.
df[['국어','수학']].mean()

국어    65.0
수학    71.0
dtype: float64

In [29]:
#그룹변 집계 정보
#반 별 국어점수의 평균
df.groupby('반')['국어'].mean()

#성별 수학 점수의 최고값
df.groupby('성별')['수학'].max()

#성별 인원수 결측치 제외한다.
df.groupby('성별')['이름'].count()

#결측치(측정되지 않은 데이터 -> 없는 데이터)
#NA -> Not Available
#NaN -> Not a Number

#반별, 성별 국어점수의 평균
df.groupby(['반','성별'])['국어'].mean()

#반별 국어, 수학 점수의 평균
df.groupby('반')[['국어','수학']].mean()

#여러 집계함수 사용
#반별 수학 점수의 평균, 최고값, 최저값, 중앙값
#agg -> Aggregation(집합)
df.groupby('반')['수학'].agg(['mean','max','min','median','count'])

    mean    max   min  median  count
반
A반  87.0   89.0  85.0    87.0      2
B반  64.6  100.0  44.0    45.0      5