In [2]:
import pandas as pd

df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 결측치가 아닌 데이터 변환 replace()

# replace 사용 후 결과를 저장하려면 inplace=True 매개변수를 추가하거나 다른 변수에 저장해야 한다.
# 모든 데이터(컬럼 구분 안 함)에서 '응시'문자열을 'Y'로 변환 잘 안 씀
df.replace('응시','Y') 
#df.replace('응시','Y', inplace=True) 

# 모든 데이터에서 '남','여' 문자열을 변경한다.
df.replace({'남':'male', '여':'female'})

# 특정 컬럼의 값을 변경
df['확인여부'].replace('확인', '1')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [ ]:
# 컬럼 추가
# 컬럼 추가, 제거는 inplace=True 대상이 아니다.
# 테이블 구조 자체가 변하는 것은 무조건 저장이 된다.
# 총점 컬럼 추가 및 국어와 수학의 합을 데이터로 삽입
# 없는 컬럼명을 넣어주면 추가된다.
df['총점'] = df['국어'] + df['수학']
#함수가 아니라서 바로 저장
df

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
2  A반  오지수  남   NaN    NaN   응시   확인    NaN
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0

In [ ]:
# 컬럼 추가, assign() 함수 사용
# assign() 함수는 컬럼 추가한 결과를 반환해준다.
# 원본은 유지하면서, 컬럼이 추가된 데이터셋을 사용할 수 있다.
# 변수를 원본데이터로 주면 원본데이터를 변결할 수 있다.

# 평균 컬럼 추가
new_df = df.assign(평균=df['총점']/2)
new_df # 평균 컬럼이 있다.
df # 평균 컬럼이 없다.

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
2  A반  오지수  남   NaN    NaN   응시   확인    NaN
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0

In [ ]:
# 데이터 삭제 drop(), 저장하려면 inplace=True 주거나 다른 변수에 저장하거나 해야한다.
# inplace=True는 함수로 만들어진 것은 거의 다 쓸 수 있다고 생각하자. 
# axis='index', axis=0 -> 행 삭제
# axis='columns', axis=1 -> 열 삭제

# 총점 컬럼 삭제
df.drop(['총점'], axis='columns')

# 국어, 수학 컬럼 삭제
df.drop(['국어','수학'], axis='columns')

# 0, 1번 째 행을 삭제
df.drop([0, 1], axis='index')

# 2번 째 행 삭제
df.drop([2], axis=0)

    반   이름 성별 응시여부 확인여부     총점
0  A반  구이서  남   응시   확인  179.0
1  B반  김이정  여   응시   확인  123.0
2  A반  오지수  남   응시   확인    NaN
3  B반  김선후  남   응시  NaN   77.0
4  A반  하진희  여   응시  NaN   85.0
5  A반  강현진  남  NaN  NaN    NaN
6  B반  김진솔  남   응시   확인  179.0
7  B반  박서준  여   응시   확인  123.0
8  A반  김성희  남  NaN   확인    NaN
9  B반  이지서  여   응시   확인  186.0